### PR TITLE
Upgrade spark to 2.2.0.cloudera2.

### PR DESCRIPTION
**Pull request by attilapiros**
Tested with sbt runMain.

### CODE REVIEW

**Comment by squito** [comment]
will this also work with cdh5.x / spark 1.x still?  Is it possible to make that conditional in the g8 template somehow?  It is still useful for us to be able to setup a spark app for cdh5 sometimes.

If its a huge pain, than don't worry about -- lets just drop a tag for the cdh5 / spark 1.x version and keep going with the spark 2 version

**Comment by attilapiros** [comment]
No it won't :(. There is [conditionals in g8](http://www.foundweekends.org/giter8/template.html#Conditionals) but I think it is too complex to use it here I mean at every place and keep the cdh_version in synch somehow...

But what about using separate branches. The sbt new is able to handle other branches, like for my fork this simply works:

```bash
sbt new attilapiros/cdh-spark.g8 --branch spark_version_upgrade
```

**Comment by squito** [comment]
ok sounds good.  lets cut a branch for c5 / spark 1.x

anything else you want to get into that line before we make a separate branch?  (of course we could update both, I just doubt we will bother ...)

**Comment by squito** [comment]
ok thanks, I made a cdh5.x_spark1.x branch.  Can you update the README as well to mention that branch?

**Comment by squito** [comment]
thanks @attilapiros !

**Pull request merged**
