### PR TITLE
fix: somehow in .gitignore */target stops g8

### PR DESCRIPTION
**Pull request by attilapiros**
Including some update for the current g8 version.

### CODE REVIEW

**Comment by squito** [comment]
thanks @attilapiros!

btw if you're interested, a couple follow-ups you could do:

* report an issue on giter8 -- maybe related to this one? https://github.com/foundweekends/giter8/issues/329

* some more clean up in this template
    * update for spark2
    * get rid of the "example" and "spark-local" projects, they're pointless now
    * maybe add another project, just as an example of multi-project builds
    * add a unit test

**Comment by attilapiros** [comment]
I will test first with the newest version as meanwhile I find out giter8 try to follow the rules of .gitignore: https://github.com/foundweekends/giter8/blob/master/library/src/main/scala/giter8/JGitIgnore.scala,

But playing with the current unit test I cannot reproduced this problem.

**Comment by attilapiros** [comment]
I cannot reproduce the bug with the new g8.
By the way to use the template g8 is not necessary needed to be installed sbt can be used as well:

```
$ sbt new squito/cdh-spark.g8 
```

**Comment by squito** [comment]
you mean if you use build g8 from the latest source, there is no error?  that's great.

cool, I didn't know that about sbt integration -- I wonder what version of sbt is required for that.  You could add that to this repos README too :)

**Comment by attilapiros** [comment]
Version 0.13.13 or above, Ok I will

**Pull request merged**
